// Generated by gencpp from file assignments/MapFilePathRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_MAPFILEPATHREQUEST_H
#define ASSIGNMENTS_MESSAGE_MAPFILEPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignments
{
template <class ContainerAllocator>
struct MapFilePathRequest_
{
  typedef MapFilePathRequest_<ContainerAllocator> Type;

  MapFilePathRequest_()
    : map_file_path()  {
    }
  MapFilePathRequest_(const ContainerAllocator& _alloc)
    : map_file_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _map_file_path_type;
  _map_file_path_type map_file_path;





  typedef boost::shared_ptr< ::assignments::MapFilePathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignments::MapFilePathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapFilePathRequest_

typedef ::assignments::MapFilePathRequest_<std::allocator<void> > MapFilePathRequest;

typedef boost::shared_ptr< ::assignments::MapFilePathRequest > MapFilePathRequestPtr;
typedef boost::shared_ptr< ::assignments::MapFilePathRequest const> MapFilePathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignments::MapFilePathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignments::MapFilePathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignments::MapFilePathRequest_<ContainerAllocator1> & lhs, const ::assignments::MapFilePathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_file_path == rhs.map_file_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignments::MapFilePathRequest_<ContainerAllocator1> & lhs, const ::assignments::MapFilePathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignments

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignments::MapFilePathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignments::MapFilePathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::MapFilePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignments::MapFilePathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::MapFilePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignments::MapFilePathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignments::MapFilePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bfcad2d18ad637a0c527a2793461f29";
  }

  static const char* value(const ::assignments::MapFilePathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bfcad2d18ad637aULL;
  static const uint64_t static_value2 = 0x0c527a2793461f29ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignments::MapFilePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignments/MapFilePathRequest";
  }

  static const char* value(const ::assignments::MapFilePathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignments::MapFilePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string map_file_path\n"
;
  }

  static const char* value(const ::assignments::MapFilePathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignments::MapFilePathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_file_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapFilePathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignments::MapFilePathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignments::MapFilePathRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_file_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.map_file_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_MAPFILEPATHREQUEST_H
