// Generated by gencpp from file assignments/MapFilePath.msg
// DO NOT EDIT!


#ifndef ASSIGNMENTS_MESSAGE_MAPFILEPATH_H
#define ASSIGNMENTS_MESSAGE_MAPFILEPATH_H

#include <ros/service_traits.h>


#include <assignments/MapFilePathRequest.h>
#include <assignments/MapFilePathResponse.h>


namespace assignments
{

struct MapFilePath
{

typedef MapFilePathRequest Request;
typedef MapFilePathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapFilePath
} // namespace assignments


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignments::MapFilePath > {
  static const char* value()
  {
    return "fad351900b5fbe0dbdabf42eace39648";
  }

  static const char* value(const ::assignments::MapFilePath&) { return value(); }
};

template<>
struct DataType< ::assignments::MapFilePath > {
  static const char* value()
  {
    return "assignments/MapFilePath";
  }

  static const char* value(const ::assignments::MapFilePath&) { return value(); }
};


// service_traits::MD5Sum< ::assignments::MapFilePathRequest> should match
// service_traits::MD5Sum< ::assignments::MapFilePath >
template<>
struct MD5Sum< ::assignments::MapFilePathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::MapFilePath >::value();
  }
  static const char* value(const ::assignments::MapFilePathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::MapFilePathRequest> should match
// service_traits::DataType< ::assignments::MapFilePath >
template<>
struct DataType< ::assignments::MapFilePathRequest>
{
  static const char* value()
  {
    return DataType< ::assignments::MapFilePath >::value();
  }
  static const char* value(const ::assignments::MapFilePathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignments::MapFilePathResponse> should match
// service_traits::MD5Sum< ::assignments::MapFilePath >
template<>
struct MD5Sum< ::assignments::MapFilePathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignments::MapFilePath >::value();
  }
  static const char* value(const ::assignments::MapFilePathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignments::MapFilePathResponse> should match
// service_traits::DataType< ::assignments::MapFilePath >
template<>
struct DataType< ::assignments::MapFilePathResponse>
{
  static const char* value()
  {
    return DataType< ::assignments::MapFilePath >::value();
  }
  static const char* value(const ::assignments::MapFilePathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENTS_MESSAGE_MAPFILEPATH_H
